# .github/release.yml

changelog:
  categories:
    - title: New Features
      labels:
        - New Feature
    - title: Bug Fixes
      labels:
        - Bug Fix
    - title: Other Changes
      labels:
        - "*"
